### ISSUE TITLE
Please check necessity of machine id mount

### ISSUE THREAD

**Issue by troublete** [tsari/build-server#2]
I just was in need to use the build-server on macOS. During the installation few problems occured. 

One of them was that in the README provided setup script suggests a mount of `/etc/machine-id` -- Mac doesn't have that, but even though I first thought this could be a crucial issue. It turned out not to be. In fact it seems that this mount isn't really necessary, because the mount directs in docker to a "not valid" etc directory, unlike the host system. So maybe this mount isn't necessary. 
:)

**Comment by tsari** [comment]
At the time of writing this build-server Dockerfile I copied the run command from different sources to build my own. My current run commands for such docker images don't have this line of code. So feel free to omit it. ;)

Furthermore I advise to use the dedicated node, composer, ... images from my docker hub instead of this all-in-one image. It was built with the purpose of a simple replacement of the "deploy server" we were using at our company.

**Comment by troublete** [comment]
Well -- I work now at said company. So alright, will update source there. Thanks for the answer! :)
